echo '/Users/javierca/Documents/slumps/results/wasms/Cartesian_product_of_two_or_more_lists.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Cartesian_product_of_two_or_more_lists.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Evaluate_binomial_coefficients.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Evaluate_binomial_coefficients.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Knuth_shuffle.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Knuth_shuffle.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Flatten_a_list.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Flatten_a_list.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Best_shuffle.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Best_shuffle.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Sierpinski_triangle.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Sierpinski_triangle.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Law_of_cosines_-_triples.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Law_of_cosines_-_triples.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Tokenize_a_string_with_escaping.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Tokenize_a_string_with_escaping.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Nth_root.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Nth_root.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Price_fraction.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Price_fraction.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Sailors,_coconuts_and_a_monkey_problem.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Sailors,_coconuts_and_a_monkey_problem.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Middle_three_digits.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Middle_three_digits.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Holidays_related_to_Easter.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Holidays_related_to_Easter.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Zeckendorf_number_representation.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Zeckendorf_number_representation.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/URL_decoding.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/URL_decoding.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/99_Bottles_of_Beer.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/99_Bottles_of_Beer.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Gray_code.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Gray_code.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Thiele's_interpolation_formula.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Thiele's_interpolation_formula.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Sort_numbers_lexicographically.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Sort_numbers_lexicographically.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Hilbert_curve.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Hilbert_curve.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Burrows–Wheeler_transform.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Burrows–Wheeler_transform.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Execute_HQ9+.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Execute_HQ9+.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Catalan_numbers.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Catalan_numbers.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Roots_of_unity.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Roots_of_unity.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Day_of_the_week.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Day_of_the_week.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Magic_squares_of_singly_even_order.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Magic_squares_of_singly_even_order.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Feigenbaum_constant_calculation.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Feigenbaum_constant_calculation.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Combinations.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Combinations.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Ramsey's_theorem.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Ramsey's_theorem.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Permutations-Rank_of_a_permutation.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Permutations-Rank_of_a_permutation.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Hofstadter-Conway_$10,000_sequence.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Hofstadter-Conway_$10,000_sequence.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Sparkline_in_unicode.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Sparkline_in_unicode.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Show_Ascii_table.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Show_Ascii_table.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Continued_fraction.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Continued_fraction.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Fibonacci_sequence.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Fibonacci_sequence.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Largest_number_divisible_by_its_digits.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Largest_number_divisible_by_its_digits.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Multiplication_tables.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Multiplication_tables.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Longest_increasing_subsequence.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Longest_increasing_subsequence.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Sorting_algorithms-Bubble_sort.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Sorting_algorithms-Bubble_sort.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/N'th.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/N'th.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Horner's_rule_for_polynomial_evaluation.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Horner's_rule_for_polynomial_evaluation.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Sorting_algorithms-Merge_sort.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Sorting_algorithms-Merge_sort.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Total_circles_area.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Total_circles_area.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Remove_duplicate_elements.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Remove_duplicate_elements.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Forward_difference.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Forward_difference.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Fast_Fourier_transform.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Fast_Fourier_transform.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Babbage_problem.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Babbage_problem.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Vampire_number.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Vampire_number.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Quickselect_algorithm.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Quickselect_algorithm.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Cycle_detection.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Cycle_detection.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Chebyshev_coefficients.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Chebyshev_coefficients.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Deconvolution-1D.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Deconvolution-1D.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Palindrome_detection.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Palindrome_detection.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/100_doors.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/100_doors.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Look-and-say_sequence.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Look-and-say_sequence.wasm' 
echo '/Users/javierca/Documents/slumps/results/wasms/Mian-Chowla_sequence.wasm' 
mill cli.run  '/Users/javierca/Documents/slumps/results/wasms/Mian-Chowla_sequence.wasm' 
