FROM slumps:latest

RUN apt-get install -y python3-pip

COPY /utils/pipeline/python /slumps/python

WORKDIR /slumps/python

ENV LANG C.UTF-8

ENV SRC_DIR /slumps
ENV WASM_LD /usr/bin/wasm-ld-8
ENV INPUT_FOLDER /input
ENV MAX_INST 3
ENV OPT1 O0
ENV OPT2 O0
ENV CHECK_OPTS ""


RUN pip3 install -r requirements.txt

CMD ["python3", "./pipeline.py"]