C2LL_MESSAGE = "C2LL"
LOG_MESSAGE  = "LOG"
LL2BC_MESSAGE = "LL2BC"
BC2Candidates_MESSAGE = "BC2Candidates"
BC2WASM_MESSAGE = "BC2WASM"
WASM2WAT_MESSAGE = "WASM2WAT"
STORE_MESSAGE = "STORE"
GENERATE_VARIANT_MESSAGE = "GENERAET_VARIANT"

# QUEUES

LL_QUEUE = "LL_QUEUE"
BC_TRANSFORMATION_QUEUE = "BC_QUEUE"
BC_EXPLORATION_QUEUE = "BC_EXPLORATION_QUEUE"
GENERATION_QUEUE = "GENERATION_QUEUE"
WASM_QUEUE = "WASM_QUEUE"
WAT_QUEUE = "WAT_QUEUE"
STORE_KEY = "STORE_KEY"
#LL_QUEUE = "LL_QUEUE"