# MESSAGE TYPE
C2LL_MESSAGE = "C2LL"
LL2BC_MESSAGE = "LL2BC"
BC2Candidates_MESSAGE = "BC2Candidates"
BC2WASM_MESSAGE = "BC2WASM"
WASM2WAT_MESSAGE = "WASM2WAT"
STORE_MESSAGE = "STORE"
NATIVE_WASMTIME_GENERATED = "NATIVE_WASMTIME_GENERATED"
GENERATE_VARIANT_MESSAGE = "GENERATE_VARIANT"
MACHINE_CODE_DUMPED = "MACHINE_CODE_DUMPED"
CROW_HEARTBEAT_GENERATED = "CROW_HEARTBEAT_GENERATED"
CROW_HEARTBEAT_NEW_PROGRAM = "CROW_HEARTBEAT_NEW_PROGRAM"
CROW_HEARTBEAT_NEW_FUNCTION = "CROW_HEARTBEAT_NEW_FUNCTION"
CROW_HEARTBEAT_NEW_VARIANT = "CROW_HEARTBEAT_NEW_VARIANT"
SPAWN_COMMAND = "CROW_SPAWN"
SPAWN_QUEUE = "CROW_SPAWN_QUEUE"

CROW_HEARTBEAT_NEW_WASM = "CROW_HEARTBEAT_NEW_WASM"
CROW_HEARTBEAT_NEW_WAT = "CROW_HEARTBEAT_NEW_WAT"
CROW_HEARTBEAT_NEW_BC = "CROW_HEARTBEAT_NEW_BC"


CROW_HEARTBEAT_KEY = "crow.heart.beat"
CROW_HEARTBEAT_KEY_NEW_PROGRAM = "crow.heart.new_program"
CROW_HEARTBEAT_KEY_NEW_FUNCTION = "crow.heart.new_function"
CROW_HEARTBEAT_KEY_NEW_VARIANT = "crow.heart.new_variant"

CROW_HEARTBEAT_KEY_NEW_BC = "crow.heart.new_bc"
CROW_HEARTBEAT_KEY_NEW_WASM = "crow.heart.new_wasm"
CROW_HEARTBEAT_KEY_NEW_WAT = "crow.heart.new_wat"

# QUEUES
LL_QUEUE = "LL_QUEUE"
BC_TRANSFORMATION_QUEUE = "BC_QUEUE"
BC_EXPLORATION_QUEUE = "BC_EXPLORATION_QUEUE"
GENERATION_QUEUE = "GENERATION_QUEUE"
WASM_QUEUE = "WASM_QUEUE"
SPLIT_QUEUE = "SPLIT_QUEUE"
WAT_QUEUE = "WAT_QUEUE"
STORE_KEY = "STORE_KEY"
LIVE_STATUS_QUEUE = "LIVE_STATUS_QUEUE"
WASMTIME_QUEUE = "WASMTIME_QUEUE"
OBJDUMP_QUEUE = "OBJDUMP_QUEUE"
DIFF_QUEUE = "DIFF_QUEUE"
CROW_HEARTBEAT_QUEUE="CROW_HEARTBEAT_QUEUE"
#LL_QUEUE = "LL_QUEUE"

# MONITORING MESSAGES
LOG_MESSAGE = "LOG"
GENERATED_WASM_VARIANT = "GENERATED_WASM_VARIANT"
GENERATED_BC_VARIANT = "GENERATED_BC_VARIANT"
EXPLORATION_RESULT = "EXPLORATION_DONE"
GENERATED_WAT_FILE = "GENERATED_WAT_FILE" # Call for alignment maybe