version: "3"  # optional since v1.27.0
services:
  
  # Generators service
  generators:
    restart: always
    image: "slumps/crow2:latest"
    volumes:
      - ./out:/slumps/crow/crow/storage/out
      - ./config.ini:/slumps/crow/crow/settings/config.ini
    entrypoint:
      - /bin/bash
    env_file:
      - .env.cr
    command: ./launch_generators.sh 5 %cache.redis-port 9898 # 1 generators


  # exploration service
  exploration:
    restart: always
    image: "slumps/crow2:latest"
    volumes:
      - ./out:/slumps/crow/crow/storage/out
      - ./config.ini:/slumps/crow/crow/settings/config.ini
    entrypoint:
      - /bin/bash
    env_file:
      - .env.cr
    command: ./launch_exploration.sh %DEFAULT.order 19,20,21,22 %DEFAULT.exploration-timeout 150 %cache.redis-port 9898 %DEFAULT.workers 2 %souper.workers 1 %DEFAULT.combinations False

      # exploration service
  exploration2:
    restart: always
    image: "slumps/crow2:latest"
    volumes:
      - ./out:/slumps/crow/crow/storage/out
      - ./config.ini:/slumps/crow/crow/settings/config.ini
    entrypoint:
      - /bin/bash
    env_file:
      - .env.cr
    command: ./launch_exploration.sh %DEFAULT.order 19,20,21,22 %DEFAULT.exploration-timeout 150 %cache.redis-port 9898 %DEFAULT.workers 2 %souper.workers 1 %DEFAULT.combinations False

  # entrypoints
  entrypoints:
    restart: always
    image: "slumps/crow2:latest"
    volumes:
      - ./out:/slumps/crow/crow/storage/out
      - ./config.ini:/slumps/crow/crow/settings/config.ini
    entrypoint:
      - /bin/bash
    env_file:
      - .env.cr
    command: ./launch_entrypoints.sh 0 10 10 %cache.redis-port 9898 # 1 workers each


