apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: slumps-distributed-
spec:
  entrypoint: slumps-distributed
  parallelism: 4
  templates:
  - name: slumps-distributed
    steps:
    - - name: download-programs
        template: download-template
    - - name: slumpsfy
        template: slumps-template
        arguments:
          parameters:
          - name: program
            value: "{{item}}"
        withParam: "{{steps.download-programs.outputs.parameters.programs}}"
        continueOn:
          failed: true
  - name: download-template
    script:
      image: madshansen/docker-git-ftp
      command: [bash]
      source: |
        apt-get update && apt-get install -y python && git clone https://github.com/KTH/slumps.git && ls -l /slumps/benchmark_programs/rossetta/bio | wc -l && python -c "import json,os;  print(json.dumps(os.listdir('/slumps/benchmark_programs/rossetta/bio')))" > /out.txt && cat /out.txt
    outputs:
      parameters:
        - name: programs
          valueFrom: 
            path: "/out.txt"
  - name: slumps-template
    retryStrategy: {}
    inputs:
      parameters:
      - name: program
    outputs:
      artifacts:
      - name: slumps
        path: /slumps/src/out
      - name: logs
        path: /slumps/src/logs
    container:
      image: "jacarte/slumps:kuber2"
      command: [/bin/bash]
      args: [start_docker.sh, "https://raw.githubusercontent.com/KTH/slumps/master/benchmark_programs/rossetta/bio/{{inputs.parameters.program}}", "{{inputs.parameters.program}}"]
      env:
      - name: TIMEOUT
        value: 21600 # 3 hours per program
      resources:
        requests:
          memory: 4Gi
          cpu: 1
    #    limits:
    #      memory: 4G
    #      cpu: 2
