apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: slumps-distributed-wasi-
spec:
  entrypoint: slumps-distributed
  parallelism: 2
  arguments:
    parameters:
    - name: repo
    - name: folder
    - name: raw
  templates:
  - name: slumps-distributed
    steps:
    - - name: download-programs
        template: download-template
    - - name: explore
        template: explore-template
        arguments:
          parameters:
          - name: program
            value: "{{item}}"
        withParam: "{{steps.download-programs.outputs.parameters.programs}}"
        continueOn:
          failed: true
  - name: download-template
    script:
      image: madshansen/docker-git-ftp
      command: [bash]
      source: |
        apt-get update && apt-get install -y python && git clone "{{workflow.parameters.repo}}" && ls -l "{{workflow.parameters.folder}}" | wc -l && python -c "import json,os;  print(json.dumps([l for l in os.listdir('{{workflow.parameters.folder}}') if  l.endswith('.c')]))" > /out.txt && cat /out.txt
    outputs:
      parameters:
        - name: programs
          valueFrom: 
            path: "/out.txt"

  - name: explore-template
    inputs:
      parameters:
        - name: program
    steps:
    - - name: slumpsfy
        template: slumps-template
        arguments:
          parameters:
          - name: program
            value: "{{item.program}}"
          - name: time1
            value: "{{item.time1}}"
          - name: time2
            value: "{{item.time2}}"
        withItems: 
          - { program: "{{inputs.parameters.program}}",time2: "0", time1: "18000" }
        continueOn:
          failed: true
  - name: slumps-template
    retryStrategy: {}
    inputs:
      parameters:
      - name: program
      - name: time1
      - name: time2
    outputs:
      artifacts:
      - name: slumps
        path: /slumps/crow/out
      - name: logs
        path: /slumps/crow/logs
    script:
      image: "slumps/crow:latest"
      command: [/bin/bash]
      source: |
        wget {{workflow.parameters.raw}}/{{inputs.parameters.program}} && mkdir -p /inputs && cp {{inputs.parameters.program}} /inputs/ && mkdir -p /slumps/crow/out/muladd && bash start_poly_bench.sh 30 %DEFAULT.order 1,2,3,4,5,6,14,15,16,17,18,19 %souper.souper-common --solver-timeout=0 %DEFAULT.timeout {{inputs.parameters.time2}} %souper.workers 10 %DEFAULT.workers 5 %DEFAULT.outfolder /slumps/crow/out %DEFAULT.exploration-timeout {{inputs.parameters.time1}} %DEFAULT.link-wasi False {{inputs.parameters.program}}
      resources:
        requests:
          memory: 2G
          cpu: 1
        limits:
          memory: 6G
          cpu: 3
