apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: slumps-simple-program-wasi-
spec:
  entrypoint: slumps-distributed
  parallelism: 5
  arguments:
    parameters:
    - name: program
  templates:
  - name: slumps-distributed
    steps:
    steps:
    - - name: slumpsfy
        template: slumps-template
        arguments:
          parameters:
          - name: program
            value: "{{workflow.parameters.program}}"
          - name: order
            value: "{{item.order}}"
        withItems: 
          - { order: "24" }
          - { order: "23" }
          - { order: "22" }
          - { order: "18" }
          - { order: "19" }
          - { order: "20" }
          - { order: "18" }
          - { order: "17" }
          - { order: "16" }
          - { order: "15" }
          - { order: "14" }
          - { order: "13" }
          - { order: "12" }
          - { order: "11" }
          - { order: "10" }
          - { order: "9" }
          - { order: "8" }
          - { order: "7" }
          - { order: "6" }
          - { order: "5" }
          - { order: "4" }
          - { order: "3" }
          - { order: "2" }
          - { order: "1" }
        continueOn:
          failed: true
  - name: slumps-template
    retryStrategy: {}
    inputs:
      parameters:
      - name: program
      - name: order
    outputs:
      artifacts:
      - name: slumps
        path: /slumps/crow/out
      - name: logs
        path: /slumps/crow/logs
    container:
      image: "jacarte/slumps:crow"
      command: [/bin/bash]
      args: [start_docker.sh,"{{inputs.parameters.program}}","-DEFAULT.order", "{{inputs.parameters.order}}", "-DEFAULT.timeout", "25200","-DEFAULT.link-wasi", "False", "-DEFAULT.generate-bc-only", "True" ]
      