# WARNING:
# This is still in testing! It still requires to set up AFL's Master-Slave mechanism.
# Also, the Socket Server does not seem to be running concurrently yet (even with a 
# thread per request).

# Create/update stack on the swarm:
# set -a
# source .env
# set +a
# docker stack deploy --compose-file docker-compose.base.yml -c docker-compose.stack.yml afl_swam

# View all (multi-instance) services of stack:
# docker service ls

# View live logs of (multi-instance) service:
# docker service logs -f {NAME_OF_THE_SERVICE}

# Remove stack from the swarm
# docker stack rm afl_swam

version: '3.7'

services:
  swam_server:
    image: fuzzer_swam_server

  afl_interface:
    image: fuzzer_afl_interface
    deploy:
      replicas: 6

volumes:
  compiled_sources:
  maven_data:
