name: Build docker souper
on:
  push:
    branches:
    - master
    paths:
    - 'docker_images/Dockerfile'

jobs:
  build:
    name: Build docker stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo
      - name: Install dependencies
        run: |
          sudo apt-get update && docker --version
      
      - name: Build souper image
        run: |
          cd docker_images && sudo docker build -t jacarte/slumps:backend -f Dockerfile .
      - name: Push souper image
        run: |
          docker login -u="$user" -p="$pass" && docker push jacarte/slumps:souper
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
      