name: Build docker images
on:
  push:
      branches:
        - master
     

jobs:
  build:
    name: Build docker stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y docker.io tree && sudo systemctl enable docker && docker --version
      - name: Build souper image
        run: |
          cd docker_images && sudo docker build -t jacarte/slumps:souper -f test.Dockerfile .
      - name: Push souper image
        run: |
          sudo docker login -u="$user" -p="$pass"
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
        
     