name: Build docker images
on:
  push:
      branches:
        - master
      # file paths to consider in the event. Optional; defaults to all.
      paths:
        - '.github/**'
     

jobs:
  build-crow-dockerrmi:
    name: Build docker stack for CROW
    runs-on: ubuntu-latest
    steps:
      - name: Checkout recursive
        uses: actions/checkout@v2 # checkout latest version of the repo
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update && docker --version
      - name: Build backend image
        run: |
          sudo bash build_docker_crow.sh
      - name: Push images Souper
        run: |
          docker login -u="$user" -p="$pass" && docker push slumps/souper:latest
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}

      - name: Push images backend
        run: |
          docker login -u="$user" -p="$pass" && docker push slumps/backend:latest
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
      - name: Push images CROW
        run: |
          docker login -u="$user" -p="$pass" && docker push slumps/crow2:latest
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}

      - name: Push images CROW
        run: |
          docker login -u="$user" -p="$pass" && docker push slumps/crow2:standalone
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
     
