name: Build wafl
on:
  pull_request:
  push:
      paths:
        - 'wasm-fuzzer/**'
     

jobs:
  build-wafl:
    name: Build wafl dependencies and client fuzzer
    runs-on: ubuntu-latest
    container:
      image: arm64v8/python:3.7-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo
        with: 
          submodules: 'true'
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y make git gcc sudo g++ default-jdk
      - name: Installing sudo
        run: |
          useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
      - name: Build
        run: |
          cd wasm-fuzzer && set AFL_NO_X86=1 && ./build.sh
      
      
     