name: Build docker images
on:
  push:
      branches:
        - master
      # file paths to consider in the event. Optional; defaults to all.
      paths:
        - 'crow/**'
        - '.github/**'
     

jobs:
  build-crow-dockerrmi:
    name: Build docker stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo
      - name: Install dependencies
        run: |
          sudo apt-get update && docker --version
      - name: Build backend image
        run: |
          sudo docker build -t slumps/crow:latest -f Dockerfile .
      - name: Push images
        run: |
          docker login -u="$user" -p="$pass" && docker push slumps/crow:latest
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
      
     