name: Build docker images
on:
  push:
      branches:
        - master
      # file paths to consider in the event. Optional; defaults to all.
      paths:
        - 'wasm-fuzzer/*/**'
     

jobs:
  build:
    name: Build docker stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo
      - name: Install dependencies
        run: |
          sudo apt-get update && docker --version
      - name: Build wafl image
        run: |
          cd wasm-fuzzer && sudo docker build -t wafl .
      - name: Push images
        run: |
          docker login -u="$user" -p="$pass" && docker push jacarte/slumps:wafl
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
      
     