name: Build souper

on: 
  push:
    paths-ignore: 
      - 'wasm-fuzzer/**'
  pull_request:
    paths-ignore: 
      - 'wasm-fuzzer/**'

jobs:
  build-macos:
    runs-on: 	macos-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: Set up
        run: brew install llvm re2c subversion go z3 ninja
        
      - name: Install redis go
        run: go get github.com/gomodule/redigo/redis

      - name: Build deps
        run: cd souper && /bin/bash build_deps.sh Release

      - name: Zip built deps
        run: cd souper && tar -zcvf souper-deps-mac.tar.gz thid_party && ls -la | grep  -i souper-deps-mac.tar.gz

      - name: Build project
        run: cd souper && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make
      
      - name: Zip folder
        run: cd souper && tar -zcvf souper-mac.tar.gz build && ls -la | grep  -i souper-mac.tar.gz