name: Build docker images
on:
  push:
      branches:
        - master
      # file paths to consider in the event. Optional; defaults to all.
      paths:
        - 'wasm-fuzzer/**'
        - '.github/**'
     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo

      - name: Install dependencies
        run: |
          sudo apt-get update
          docker --version

      - name: Build wafl image
        run: |
          cd wasm-fuzzer
          docker build -t wafl .

      - name: Test wafl container
        run: ./docker_staging_check.sh

      - name: Push images
        run: |
          docker tag wafl slumps/wafl:latest
          docker login -u="$user" -p="$pass"
          docker push slumps/wafl:latest
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
      
     