name: COMPILE_AND_VALIDATE

on:
  push:
    paths:
      # '*' matches any character except '/'
      - 'benchmark_programs/*'
      - 'benchmark_programs/*/*'
      - 'benchmark_programs/*/*/*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run python script to compile and validate
      run: python3 ./utils/compile_and_verify/compile_and_verify.py linux benchmark_programs  
    - name: GIT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git remote add origin-tok https://Jacarte:${GITHUB_TOKEN}@github.com/KTH/slumps.git && git remote remove origin
      
    - name: GIT
      run: git config --global user.email "javierca@kth.se" && git config --global user.name "Jacarte" 
      
    - name: GIT
      run: git checkout -b master && git add ./utils/compile_and_verify && git commit -m 'Compiling and validating' 
      
    - name: GIT
      run: git push origin-tok master
    