name: CROW on file
on:
  push:
      branches:
        - master
      tags:
        - v1
      # file paths to consider in the event. Optional; defaults to all.
      paths:
        - 'benchmark_programs/*/**'

jobs:
  build:
    name: CROW
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo
      - name: Process path
        run: |
          python3 python3 get_payload.py '$(git log --oneline --format=%B -n 1 HEAD)' && cd crow && ./run.sh $(python3 get_payload.py '$(git log --oneline --format=%B -n 1 HEAD)') || true
      - name: Archive crow results
        uses: actions/upload-artifact@v1
        with:
          name: crow_out
          path: ./crow/crow_out