name: CROW on file

push:
    branches:
      - master
    tags:
      - v1
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'benchmark_programs/*'

jobs:
  build:
    name: CROW
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
          uses: actions/checkout@v2 # checkout latest version of the repo
      - name: Get file changes
          id: get_file_changes
          uses: dorner/file-changes-action@v1.2.0
          with:
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            plaintext: true
      - name: Echo file changes
          run: |
            echo Changed files: ${{ steps.get_file_changes.outputs.files }}